name: PR Check

on:
  pull_request:
    branches: [main, dev-*]

jobs:
  lint-and-build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "23.5.0"

      - name: Install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install && npm ci

      - name: Run ESLint
        run: npm eslint .

      - name: Run Prettier check
        run: npm prettier --check .

      - name: Type check
        run: npm tsc --noEmit

      - name: Build
        run: npm run build
